apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx1
  name: nginx1
spec:
  replicas: 2
  selector:
    matchLabels:
      run: nginx1
  template:
    metadata:
      labels:
        run: nginx1
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m

